### ISSUE TITLE
为什么会出现这样的情况

### ISSUE THREAD

**Issue by snake-lvyonghao** [bla58351/tyut-novpn#4]
[注意] VPN已连接，但无法连接至内网

**Comment by bla58351** [comment]
是连接时就提示吗

**Comment by snake-lvyonghao** [comment]
> 是连接时就提示吗

centenos 服务器重启后 输入 tyut就是这样 反而之前的connect.sh脚本可以使用

**Comment by bla58351** [comment]
有完整的连接时的输出吗

**Comment by snake-lvyonghao** [comment]
login successfully!
starting vpn...
Connect successfully!
Vpn is connected!
﻿[注意] VPN已连接，但无法连接至内网

**Comment by bla58351** [comment]
> login successfully!
> starting vpn...
> Connect successfully!
> Vpn is connected!
> ﻿[注意] VPN已连接，但无法连接至内网

连接之后ping一下`202.207.240.67`和`202.207.247.49`看看通不通

**Comment by snake-lvyonghao** [comment]
> > login successfully!
> 
> > starting vpn...
> 
> > Connect successfully!
> 
> > Vpn is connected!
> 
> > ﻿[注意] VPN已连接，但无法连接至内网
> 
> 
> 
> 连接之后ping一下`202.207.240.67`和`202.207.247.49`看看通不通


202.207.240.67可以 202.207.247.49 不行

**Comment by bla58351** [comment]
> > > login successfully!
> > 
> > 
> > > starting vpn...
> > 
> > 
> > > Connect successfully!
> > 
> > 
> > > Vpn is connected!
> > 
> > 
> > > [注意] VPN已连接，但无法连接至内网
> > 
> > 
> > 连接之后ping一下`202.207.240.67`和`202.207.247.49`看看通不通
> 
> 202.207.240.67可以 202.207.247.49 不行

emm...
`202.207.247.49`似乎禁ping了，我反代能上去但也ping不通😂
你再ping一下`202.207.240.147`试试

**Comment by snake-lvyonghao** [comment]
> > > > login successfully!
> > > 
> > > 
> > > > starting vpn...
> > > 
> > > 
> > > > Connect successfully!
> > > 
> > > 
> > > > Vpn is connected!
> > > 
> > > 
> > > > [注意] VPN已连接，但无法连接至内网
> > > 
> > > 
> > > 连接之后ping一下`202.207.240.67`和`202.207.247.49`看看通不通
> > 
> > 
> > 202.207.240.67可以 202.207.247.49 不行
> 
> emm...
> `202.207.247.49`似乎禁ping了，我反代能上去但也ping不通😂
> 你再ping一下`202.207.240.147`试试

The vpnd process fails to disconnect the VPN connection!
[信息] MotionPro已停止
[注意] Vpnd not running, starting
Vpn current status is not idle, please stop the connection first!
[错误] MotionPro连接失败
重连一直都会显示连接没断开

**Comment by bla58351** [comment]
> > > > > login successfully!
> > > > 
> > > > 
> > > > > starting vpn...
> > > > 
> > > > 
> > > > > Connect successfully!
> > > > 
> > > > 
> > > > > Vpn is connected!
> > > > 
> > > > 
> > > > > [注意] VPN已连接，但无法连接至内网
> > > > 
> > > > 
> > > > 连接之后ping一下`202.207.240.67`和`202.207.247.49`看看通不通
> > > 
> > > 
> > > 202.207.240.67可以 202.207.247.49 不行
> > 
> > 
> > emm...
> > `202.207.247.49`似乎禁ping了，我反代能上去但也ping不通😂
> > 你再ping一下`202.207.240.147`试试
> 
> The vpnd process fails to disconnect the VPN connection!
> [信息] MotionPro已停止
> [注意] Vpnd not running, starting
> Vpn current status is not idle, please stop the connection first!
> [错误] MotionPro连接失败
> 重连一直都会显示连接没断开

这个好像跟我同学的问题相似
我找台机子试试能不能复现吧

**Comment by snake-lvyonghao** [comment]
[root@VM_0_10_centos bin]# ps -ef | grep tyut
root      2346  1741  0 12:39 pts/0    00:00:00 bash /usr/local/bin/tyut
root      2362  2346  0 12:39 pts/0    00:00:00 /bin/sh /usr/bin/MotionPro -h vpn1.tyut.edu.cn -u （用户名） -p （密码）
root      2366  2362  0 12:39 pts/0    00:00:00 /opt/MotionPro/vpn_cmdline -h vpn1.tyut.edu.cn -u（用户名） -p （密码）
root      3519  1741  0 12:45 pts/0    00:00:00 grep --color=auto tyut
我看了下后台一直是这个样子的 用户名和密码我就不放上来了

**Comment by snake-lvyonghao** [comment]
> > > > > > login successfully!
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > starting vpn...
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > Connect successfully!
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > Vpn is connected!
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > [注意] VPN已连接，但无法连接至内网
> 
> > > > > 
> 
> > > > > 
> 
> > > > > 连接之后ping一下`202.207.240.67`和`202.207.247.49`看看通不通
> 
> > > > 
> 
> > > > 
> 
> > > > 202.207.240.67可以 202.207.247.49 不行
> 
> > > 
> 
> > > 
> 
> > > emm...
> 
> > > `202.207.247.49`似乎禁ping了，我反代能上去但也ping不通😂
> 
> > > 你再ping一下`202.207.240.147`试试
> 
> > 
> 
> > The vpnd process fails to disconnect the VPN connection!
> 
> > [信息] MotionPro已停止
> 
> > [注意] Vpnd not running, starting
> 
> > Vpn current status is not idle, please stop the connection first!
> 
> > [错误] MotionPro连接失败
> 
> > 重连一直都会显示连接没断开
> 
> 
> 
> 这个好像跟我同学的问题相似
> 
> 我找台机子试试能不能复现吧

重启服务器，重新连接可以了，重连目前只能靠重启

**Comment by bla58351** [comment]
> > > > > > > login successfully!
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > starting vpn...
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > Connect successfully!
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > Vpn is connected!
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > [注意] VPN已连接，但无法连接至内网
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > 连接之后ping一下`202.207.240.67`和`202.207.247.49`看看通不通
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > 202.207.240.67可以 202.207.247.49 不行
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > emm...
> > 
> > 
> > > > `202.207.247.49`似乎禁ping了，我反代能上去但也ping不通😂
> > 
> > 
> > > > 你再ping一下`202.207.240.147`试试
> > 
> > 
> > > 
> > 
> > 
> > > The vpnd process fails to disconnect the VPN connection!
> > 
> > 
> > > [信息] MotionPro已停止
> > 
> > 
> > > [注意] Vpnd not running, starting
> > 
> > 
> > > Vpn current status is not idle, please stop the connection first!
> > 
> > 
> > > [错误] MotionPro连接失败
> > 
> > 
> > > 重连一直都会显示连接没断开
> > 
> > 
> > 这个好像跟我同学的问题相似
> > 我找台机子试试能不能复现吧
> 
> 重启服务器，重新连接可以了，重连目前只能靠重启

我在阿里云、华为云的centos7上试了，没法复现。
不过试的过程中也发现了一些问题，所以还是要谢谢你。
如果你发现了解决方法，欢迎pr。

**Comment by snake-lvyonghao** [comment]
我可能找到了问题所在
第一个问题：时间一长vpn虽然在连接，但是无法访问内网，应该是学校那边有着超时自动断开。
第二个问题，我在tyut check后显示[注意] VPN已连接，但无法连接至内网，尝试tyut restart ，有如下信息The vpnd process fails to disconnect the VPN connection!
[信息] MotionPro已停止
[注意] Vpnd not running, starting
Vpn current status is not idle, please stop the connection first!
[错误] MotionPro连接失败
我使用ps -ef ｜ grep vpnd 发现vpnd进程确实没有关闭，手动关闭后，再尝试tyut restart成功登上校园网

**Comment by bla58351** [comment]
> 第一个问题：时间一长vpn虽然在连接，但是无法访问内网，应该是学校那边有着超时自动断开。 
 
这个之前已经发现了，写了利用crontab重连的逻辑，不过写的太bug了没起作用，在https://github.com/bla58351/tyut-novpn/commit/cbbbbc166909de90b7ed3155d6ddee4712a75ca4 https://github.com/bla58351/tyut-novpn/commit/f62a4affa11a17f32f787f7a76252e4ad3564c59 和 https://github.com/bla58351/tyut-novpn/commit/4419590ad0d1b3a1c2ab99ad40f838d3a7f0ce24 已经修了，目前没有掉线

> 第二个问题，我在tyut check后显示[注意] VPN已连接，但无法连接至内网，尝试tyut restart ，有如下信息The vpnd process fails to disconnect the VPN connection!
[信息] MotionPro已停止
[注意] Vpnd not running, starting
Vpn current status is not idle, please stop the connection first!
[错误] MotionPro连接失败
我使用ps -ef ｜ grep vpnd 发现vpnd进程确实没有关闭，手动关闭后，再尝试tyut restart成功登上校园网  

脚本stop函数有写杀死vpnd的，难道是又写了个bug🤣
用啥指令杀死的，欢迎pr

**Comment by snake-lvyonghao** [comment]
> > 第一个问题：时间一长vpn虽然在连接，但是无法访问内网，应该是学校那边有着超时自动断开。 
> 
>  
> 
> 这个之前已经发现了，写了利用crontab重连的逻辑，不过写的太bug了没起作用，在https://github.com/bla58351/tyut-novpn/commit/cbbbbc166909de90b7ed3155d6ddee4712a75ca4 https://github.com/bla58351/tyut-novpn/commit/f62a4affa11a17f32f787f7a76252e4ad3564c59 和 https://github.com/bla58351/tyut-novpn/commit/4419590ad0d1b3a1c2ab99ad40f838d3a7f0ce24 已经修了，目前没有掉线
> 
> 
> 
> > 第二个问题，我在tyut check后显示[注意] VPN已连接，但无法连接至内网，尝试tyut restart ，有如下信息The vpnd process fails to disconnect the VPN connection!
> 
> [信息] MotionPro已停止
> 
> [注意] Vpnd not running, starting
> 
> Vpn current status is not idle, please stop the connection first!
> 
> [错误] MotionPro连接失败
> 
> 我使用ps -ef ｜ grep vpnd 发现vpnd进程确实没有关闭，手动关闭后，再尝试tyut restart成功登上校园网  
> 
> 
> 
> 脚本stop函数有写杀死vpnd的，难道是又写了个bug🤣
> 
> 用啥指令杀死的，欢迎pr

kill -9 vpnd
